[package]
name = "immune"
version = "1.0.0"
authors = []

[addresses]
immune_addr='7fb2558df47a4b6afdf46089eccbb6b2e4c2fd0808c13f2a059e8ba3a8980726'

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
